"""PDF renderer for IC memos using WeasyPrint.

Produces a professionally styled PDF with a dark header, clean typography,
section dividers, and page numbers.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime

from agents.memo.prompts import SECTION_CONFIG

logger = logging.getLogger(__name__)

# WeasyPrint import is deferred to runtime so the module loads even when
# system libraries (pango, gobject) are not present.
_HTML = None

try:
    from weasyprint import HTML

    _HTML = HTML
except Exception as exc:  # pragma: no cover
    logger.warning("WeasyPrint import failed (%s). PDF generation will fall back to HTML.", exc)


# ── HTML Template ─────────────────────────────────────────────────────────────

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Investment Committee Memo — {company_name}</title>
  <style>
    @page {{
      size: A4;
      margin: 60px 50px 70px 50px;
      @bottom-center {{
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9pt;
        color: #666;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      }}
      @top-center {{
        content: "CONFIDENTIAL — Investment Committee Memo";
        font-size: 8pt;
        color: #888;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        letter-spacing: 1px;
        text-transform: uppercase;
      }}
    }}

    body {{
      font-family: "Georgia", "Times New Roman", serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #222;
      margin: 0;
      padding: 0;
    }}

    /* Header block */
    .memo-header {{
      background: #1a1a2e;
      color: #fff;
      padding: 30px 40px;
      margin: -60px -50px 40px -50px;
    }}
    .memo-header h1 {{
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 22pt;
      font-weight: 600;
      margin: 0 0 8px 0;
      letter-spacing: 0.5px;
    }}
    .memo-header .subtitle {{
      font-size: 10pt;
      color: #b0b0c0;
      margin: 0;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }}
    .memo-header .meta {{
      font-size: 9pt;
      color: #8888a0;
      margin-top: 12px;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }}

    /* Section styling */
    .section {{
      margin-bottom: 30px;
      page-break-inside: avoid;
    }}
    .section-title {{
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 13pt;
      font-weight: 600;
      color: #1a1a2e;
      border-bottom: 2px solid #1a1a2e;
      padding-bottom: 6px;
      margin-bottom: 14px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }}
    .section-content {{
      text-align: justify;
    }}
    .section-content p {{
      margin: 0 0 10px 0;
    }}
    .section-content ul {{
      margin: 0 0 10px 0;
      padding-left: 20px;
    }}
    .section-content li {{
      margin-bottom: 4px;
    }}

    /* Divider */
    .divider {{
      border: none;
      border-top: 1px solid #ddd;
      margin: 30px 0;
    }}

    /* Footer note */
    .footer-note {{
      font-size: 8pt;
      color: #888;
      margin-top: 40px;
      border-top: 1px solid #ddd;
      padding-top: 10px;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }}
  </style>
</head>
<body>
  <div class="memo-header">
    <h1>{company_name}</h1>
    <p class="subtitle">Investment Committee Memo</p>
    <p class="meta">Generated: {generated_date} &nbsp;|&nbsp; Total Words: {total_words} &nbsp;|&nbsp; Confidence: {confidence:.0%}</p>
  </div>

  {sections_html}

  <hr class="divider">
  <p class="footer-note">
    This memo was generated by the AI-Driven PE Investment Platform.
    All content is confidential and intended for internal investment committee use only.
  </p>
</body>
</html>
"""


SECTION_HTML_TEMPLATE = """<div class="section">
  <div class="section-title">{display_name}</div>
  <div class="section-content">
    {content_html}
  </div>
</div>
"""


def _escape_html(text: str) -> str:
    """Minimal HTML escape for user-generated content."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _markdownish_to_html(text: str) -> str:
    """Convert simple markdown-like formatting to HTML paragraphs and lists."""
    lines = text.splitlines()
    paragraphs: list[str] = []
    current_para: list[str] = []
    in_list = False
    list_items: list[str] = []

    def flush_para() -> None:
        nonlocal current_para
        if current_para:
            joined = " ".join(current_para).strip()
            if joined:
                paragraphs.append(f"<p>{_escape_html(joined)}</p>")
            current_para = []

    def flush_list() -> None:
        nonlocal in_list, list_items
        if in_list and list_items:
            items_html = "\n".join(f"<li>{_escape_html(item)}</li>" for item in list_items)
            paragraphs.append(f"<ul>\n{items_html}\n</ul>")
            list_items = []
            in_list = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            flush_para()
            flush_list()
            continue

        # Bullet detection
        if stripped.startswith("- ") or stripped.startswith("* "):
            flush_para()
            in_list = True
            list_items.append(stripped[2:].strip())
        elif stripped.startswith("• "):
            flush_para()
            in_list = True
            list_items.append(stripped[2:].strip())
        else:
            flush_list()
            current_para.append(stripped)

    flush_para()
    flush_list()

    return "\n".join(paragraphs) if paragraphs else f"<p>{_escape_html(text)}</p>"


async def render_memo_pdf(memo_sections: dict | None, company_name: str) -> str:
    """Render memo sections as a styled PDF using WeasyPrint.

    Args:
        memo_sections: Dict mapping section keys to dicts with "content", "word_count", "confidence_score".
        company_name: Name of the target company for the header.

    Returns:
        Absolute path to the generated PDF file.
    """
    memo_sections = memo_sections or {}
    sections_html_parts = []
    for key, display_name, _ in SECTION_CONFIG:
        section = memo_sections.get(key, {})
        content = section.get("content", "")
        content_html = _markdownish_to_html(content)
        sections_html_parts.append(
            SECTION_HTML_TEMPLATE.format(
                display_name=_escape_html(display_name),
                content_html=content_html,
            )
        )

    total_words = sum(
        s.get("word_count", 0) for s in memo_sections.values()
    )
    avg_confidence = (
        sum(s.get("confidence_score", 0.0) for s in memo_sections.values())
        / len(memo_sections)
        if memo_sections
        else 0.0
    )

    html_content = HTML_TEMPLATE.format(
        company_name=_escape_html(company_name),
        generated_date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        total_words=total_words,
        confidence=avg_confidence,
        sections_html="\n<hr class=\"divider\">\n".join(sections_html_parts),
    )

    output_dir = os.path.join("outputs", "memos")
    os.makedirs(output_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = company_name.replace(" ", "_").replace("/", "_")

    if _HTML is not None:
        filename = f"{safe_name}_{timestamp}.pdf"
        pdf_path = os.path.join(output_dir, filename)
        _HTML(string=html_content).write_pdf(pdf_path)
        return os.path.abspath(pdf_path)

    # Fallback: write HTML if WeasyPrint is unavailable
    logger.warning("WeasyPrint unavailable; falling back to HTML output.")
    filename = f"{safe_name}_{timestamp}.html"
    html_path = os.path.join(output_dir, filename)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    return os.path.abspath(html_path)
