"""dashboard_scoring

Revision ID: c3d4e5f6g7h8
Revises: b2c3d4e5f6g7
Create Date: 2026-07-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3d4e5f6g7h8"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6g7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create deal scoring and activity log tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deal_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("financials_score", sa.Integer(), nullable=True),
        sa.Column("moat_score", sa.Integer(), nullable=True),
        sa.Column("market_score", sa.Integer(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.String(length=20), nullable=False, server_default="INSUFFICIENT"),
        sa.Column("methodology_version", sa.String(length=20), nullable=False, server_default="1.0.0"),
        sa.Column("override_score", sa.Integer(), nullable=True),
        sa.Column("override_by", sa.Integer(), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deal_pipeline.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id"),
    )

    op.create_table(
        "score_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("financials", sa.Integer(), nullable=True),
        sa.Column("moat", sa.Integer(), nullable=True),
        sa.Column("market", sa.Integer(), nullable=True),
        sa.Column("risk", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("methodology_version", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deal_pipeline.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_score_history_deal_time",
        "score_history",
        ["deal_id", "created_at"],
        postgresql_ops={"created_at": "DESC"},
    )

    op.create_table(
        "activity_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deal_pipeline.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop deal scoring and activity log tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_log")
    op.drop_index("idx_score_history_deal_time", table_name="score_history")
    op.drop_table("score_history")
    op.drop_table("deal_scores")
    # ### end Alembic commands ###
