"""signals_market_pulse

Revision ID: d4e5f6g7h8i9
Revises: c3d4e5f6g7h8
Create Date: 2026-07-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4e5f6g7h8i9"
down_revision: Union[str, Sequence[str], None] = "c3d4e5f6g7h8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create signals and market_pulse_settings tables; add status and resolved_at to intelligence_questions."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evidence_url", sa.String(length=500), nullable=True),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("confidence", sa.String(length=20), nullable=False, server_default="MEDIUM"),
        sa.Column("detected_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["deal_id"], ["deal_pipeline.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_signals_deal_time",
        "signals",
        ["deal_id", "detected_at"],
        postgresql_ops={"detected_at": "DESC"},
    )
    op.create_index(
        "idx_signals_type",
        "signals",
        ["signal_type"],
    )

    op.create_table(
        "market_pulse_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )

    op.add_column(
        "intelligence_questions",
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
    )
    op.add_column(
        "intelligence_questions",
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop signals and market_pulse_settings tables; remove status and resolved_at from intelligence_questions."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intelligence_questions", "resolved_at")
    op.drop_column("intelligence_questions", "status")
    op.drop_table("market_pulse_settings")
    op.drop_index("idx_signals_type", table_name="signals")
    op.drop_index("idx_signals_deal_time", table_name="signals")
    op.drop_table("signals")
    # ### end Alembic commands ###
