"""Add investment decision platform tables

Revision ID: 46417ac6cab7
Revises: d4e5f6g7h8i9
Create Date: 2026-07-02 00:00:41.747438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46417ac6cab7'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confidence_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('bottlenecks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_pipeline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_confidence_ledger_deal_version', 'confidence_ledgers', ['deal_id', sa.literal_column('version DESC')], unique=False)
    op.create_table('deal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('VIEW_UPDATED', 'EVIDENCE_REFRESHED', 'DILIGENCE_STATUS_CHANGED', 'CONFIDENCE_RECALCULATED', 'RECOMMENDATION_CHANGED', 'STAGE_CHANGED', name='deal_event_type'), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'USER', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_pipeline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_events_deal_time', 'deal_events', ['deal_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('investment_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('authored_by', sa.String(length=50), nullable=False),
    sa.Column('edited_by', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'FINAL', name='investment_view_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_pipeline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'version', name='uq_investment_view_deal_version')
    )
    op.create_table('diligence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='diligence_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('BLOCKER', 'HIGH', 'MEDIUM', 'LOW', name='diligence_priority'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_pipeline.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_a_id', sa.Integer(), nullable=False),
    sa.Column('evidence_b_id', sa.Integer(), nullable=False),
    sa.Column('conflict_description', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.Enum('OPEN', 'RESOLVED', 'OVERRIDDEN', name='resolution_status'), nullable=False),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_a_id'], ['evidence_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_b_id'], ['evidence_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE TYPE evidence_status AS ENUM ('VERIFIED', 'NEEDS_VALIDATION', 'CONFLICTING', 'UNKNOWN')")
    op.add_column('evidence_items', sa.Column('evidence_status', sa.Enum('VERIFIED', 'NEEDS_VALIDATION', 'CONFLICTING', 'UNKNOWN', name='evidence_status', create_type=False), nullable=False))
    op.add_column('evidence_items', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('evidence_items', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_items', 'verified_at')
    op.drop_column('evidence_items', 'verified_by')
    op.drop_column('evidence_items', 'evidence_status')
    op.execute("DROP TYPE IF EXISTS evidence_status")
    op.drop_table('evidence_conflicts')
    op.drop_table('diligence_items')
    op.drop_table('investment_views')
    op.drop_index('idx_deal_events_deal_time', table_name='deal_events')
    op.drop_table('deal_events')
    op.drop_index('idx_confidence_ledger_deal_version', table_name='confidence_ledgers')
    op.drop_table('confidence_ledgers')
    # ### end Alembic commands ###
