"""intelligence_hub_schema

Revision ID: a1b2c3d4e5f6
Revises: 5e88d99b2da6
Create Date: 2025-06-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '5e88d99b2da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create Intelligence Hub tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'),
    sa.Column('executive_briefing', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_pipeline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intelligence_hubs_company_id', 'intelligence_hubs', ['company_id'], unique=False)

    op.create_table('intelligence_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['intelligence_hubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intelligence_questions_hub_id', 'intelligence_questions', ['hub_id'], unique=False)
    op.create_index('ix_intelligence_questions_category', 'intelligence_questions', ['category'], unique=False)

    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('is_supporting', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('is_contradictory', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['intelligence_hubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['intelligence_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_items_hub_id', 'evidence_items', ['hub_id'], unique=False)
    op.create_index('ix_evidence_items_question_id', 'evidence_items', ['question_id'], unique=False)

    op.create_table('source_confidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['intelligence_hubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_confidence_hub_id', 'source_confidence', ['hub_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop Intelligence Hub tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_confidence')
    op.drop_table('evidence_items')
    op.drop_table('intelligence_questions')
    op.drop_table('intelligence_hubs')
    # ### end Alembic commands ###
